[tox]
# Minimum support: 3.11.
env_list =
	py311
	py312
	py313
	typecheck
# Always use latest version
minversion = 4.12.0
isolated_build = true

[gh-actions]
python =
	3.11: py311, typecheck
	3.12: py312
	3.13: py313

[testenv]
setenv =
	PYTHONPATH = {toxinidir}
deps =
	.[dev]
commands =
	pytest

[testenv:typecheck]
basepython = 3.11
deps =
	.[dev]
# PyCharm too.
commands =
	mypy
	pyright
