# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries
# https://docs.pypi.org
#   https://docs.pypi.org/trusted-publishers/adding-a-publisher/
#   https://docs.pypi.org/trusted-publishers/creating-a-project-through-oidc/

name: Release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      contents: read
      id-token: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        # Docs: https://github.com/actions/checkout
      -
        name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      -
        name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      -
        name: Build
        run: python -m build
      -
        name: Publish
        # Use latest
        uses: pypa/gh-action-pypi-publish@v1.8.11
